In [1]:
import numpy as np

In [2]:
b = np.array([[3,20,99],[-13,4.5,26],[0,-1,20],[5,78,-19]])   
b

array([[  3. ,  20. ,  99. ],
       [-13. ,   4.5,  26. ],
       [  0. ,  -1. ,  20. ],
       [  5. ,  78. , -19. ]])

b here is a 2 dimensional array , we can quickly determine size of each dimension by looking at shape attribute of an array 

In [3]:
b.shape

(4, 3)

dimension in numpy arrays are refered as axis, 2d arrays have two axis , labeled as 0 and 1. 

Since there are two dimension here we'll need to pass double indices while accessing them. counting along both the axes starts with 0

if we want to extract value -1 from the array created above , we will need to access it with its indices across both the axes. which are 2 and 1

In [4]:
b[2,1]

-1.0

For better understanding we can consider the first index to be index of the list where the element is , and second to be its index within that list. Indexing and slicing here works just as it worked for lists , just in two dimensions. lets look at few more examples

In [5]:
print(b)
b[:,1]

[[  3.   20.   99. ]
 [-13.    4.5  26. ]
 [  0.   -1.   20. ]
 [  5.   78.  -19. ]]


array([20. ,  4.5, -1. , 78. ])

as we can see , this simply gives us 2nd element from all the lists, and this gives us all the elements from the 2nd ist

In [6]:
b[1,:]

array([-13. ,   4.5,  26. ])

by default we can access all the elements of a single list in a 2d array by providing a single index as well

In [7]:
b[1]

array([-13. ,   4.5,  26. ])

we can pass lists of indices as well to access multiple elements of a 2d array

In [8]:
b

array([[  3. ,  20. ,  99. ],
       [-13. ,   4.5,  26. ],
       [  0. ,  -1. ,  20. ],
       [  5. ,  78. , -19. ]])

In [9]:
b[[0,1,1],[1,2,1]]

array([20. , 26. ,  4.5])

here elements will come from pairing of indices , (0,1) , (1,2) and (1,1)

we can use thin index access for modification as well

In [10]:
print(b)
b[[0,1,1],[1,2,1]]=[-10,-20,-30]
print(b)

[[  3.   20.   99. ]
 [-13.    4.5  26. ]
 [  0.   -1.   20. ]
 [  5.   78.  -19. ]]
[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


we can see that corresponding elements are now changed to new values 

we subset an array on the basis of condition also

In [11]:
b

array([[  3., -10.,  99.],
       [-13., -30., -20.],
       [  0.,  -1.,  20.],
       [  5.,  78., -19.]])

In [12]:
b>0

array([[ True, False,  True],
       [False, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [13]:
b[b>0]

array([ 3., 99., 20.,  5., 78.])

In [14]:
b[2]>=0

array([ True, False,  True])

In [15]:
print(b)
b[:,b[2]>=0]

[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


array([[  3.,  99.],
       [-13., -20.],
       [  0.,  20.],
       [  5., -19.]])

In [16]:
b[2]>=0

array([ True, False,  True])

this condition gets applied across all the lists and they have dimension size as 3 

if we wanted to apply the condition to first element of each list and then wanted to keep all corresponding elements across lists, we will have to write it like this 

In [17]:
b

array([[  3., -10.,  99.],
       [-13., -30., -20.],
       [  0.,  -1.,  20.],
       [  5.,  78., -19.]])

In [18]:
b[:,2]>=0

array([ True, False,  True, False])

In [19]:
print(b)
b[b[:,2]>=0,:]

[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


array([[  3., -10.,  99.],
       [  0.,  -1.,  20.]])

If we wanted to apply functions which work on multiple values or across a full dimension instead of single value , we will need to use numpy function instead of math package function because they work on scalars of single values . Lets try using them anyway , lets say we wanted to replace the entire 2nd list ( index =1 ) with its aboslute values.

In [20]:
import math as m


In [21]:
b[1]

array([-13., -30., -20.])

In [22]:
m.fabs(b[1])

TypeError: only size-1 arrays can be converted to Python scalars

In [23]:
b[1]=m.fabs(b[1])

TypeError: only size-1 arrays can be converted to Python scalars

In [24]:
np.abs(b[1])

array([13., 30., 20.])

In [25]:
print(b)
b[1]=np.abs(b[1])
print(b)

[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]
[[  3. -10.  99.]
 [ 13.  30.  20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


there are multiple such functions available in numpy we can write np. and then hit tab to show you the list of such functions 

In [26]:
print(b)
b[1]=np.sqrt(b[1])
print(b)

[[  3. -10.  99.]
 [ 13.  30.  20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]
[[  3.         -10.          99.        ]
 [  3.60555128   5.47722558   4.47213595]
 [  0.          -1.          20.        ]
 [  5.          78.         -19.        ]]


these functions can work across dimensions or multiple values at once 

to better understand idea of axis labels 0 and 1 , we will look at a function which collapses the array 

In [27]:
np.sum(b)

188.55491280551524

this simply sums the entire array , now lets instead of this we wanted sum across axis 0 

In [28]:
b

array([[  3.        , -10.        ,  99.        ],
       [  3.60555128,   5.47722558,   4.47213595],
       [  0.        ,  -1.        ,  20.        ],
       [  5.        ,  78.        , -19.        ]])

In [29]:
print(b)
np.sum(b,axis=0)

[[  3.         -10.          99.        ]
 [  3.60555128   5.47722558   4.47213595]
 [  0.          -1.          20.        ]
 [  5.          78.         -19.        ]]


array([ 11.60555128,  72.47722558, 104.47213595])

axis 0 here corresponds to elements across the lists , axis=1 corresponds to with in the list elements 

In [30]:

print(b)
np.sum(b,axis=1)

[[  3.         -10.          99.        ]
 [  3.60555128   5.47722558   4.47213595]
 [  0.          -1.          20.        ]
 [  5.          78.         -19.        ]]


array([92.        , 13.55491281, 19.        , 64.        ])

In [31]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [33]:
np.arange(2,8,0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

In [34]:
np.linspace(start=2,stop=10,num=15)

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

In [35]:
(10-2)/14

0.5714285714285714

here argument num essentially represent number of elements in sequence , elements in sequence are natuarlly equally spaced .

we can also create new arrays by randomly sampling an original array, or simply creating an array with random numbers using random package within numpy

In [36]:
np.random.randint(high=10,low=1,size=(2,3))

array([[3, 9, 4],
       [1, 4, 2]])

In [37]:
np.random.randint(high=10,low=1,size=(2,))

array([4, 7])

In [38]:
np.random.randint(high=10,low=1,size=2)

array([2, 3])

In [39]:
np.random.randint(high=10,low=1,size=[2])

array([1, 7])

In [40]:
np.random.random(size=(3,4))

array([[0.6534525 , 0.6996018 , 0.38889764, 0.12036975],
       [0.4851297 , 0.64053841, 0.89693529, 0.10398516],
       [0.16767477, 0.57926413, 0.94796428, 0.25338655]])

In [41]:
x=np.arange(10)

In [42]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.random.choice(x,4)

array([3, 0, 4, 1])

In [44]:
np.random.choice(x,6,replace=False)

array([5, 3, 6, 0, 7, 8])

In [45]:
y=np.random.choice(['a','b'],6)
print(y)

['a' 'a' 'a' 'b' 'a' 'a']


In [46]:
y=np.random.choice(['a','b'],1000)


In [47]:
y

array(['b', 'a', 'a', 'a', 'b', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
       'b', 'b', 'b', 'b', 'a', 'a', 'a', 'b', 'a', 'a', 'a', 'a', 'a',
       'b', 'a', 'b', 'b', 'a', 'b', 'a', 'b', 'b', 'b', 'a', 'a', 'a',
       'a', 'a', 'b', 'a', 'a', 'b', 'a', 'a', 'a', 'a', 'b', 'a', 'a',
       'a', 'a', 'b', 'b', 'a', 'a', 'a', 'b', 'a', 'a', 'a', 'a', 'a',
       'b', 'b', 'b', 'a', 'a', 'b', 'a', 'a', 'a', 'b', 'b', 'a', 'a',
       'a', 'b', 'a', 'b', 'a', 'b', 'b', 'a', 'a', 'b', 'b', 'a', 'a',
       'b', 'b', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'a', 'a', 'a', 'b',
       'a', 'a', 'b', 'a', 'b', 'b', 'b', 'a', 'b', 'a', 'a', 'a', 'b',
       'a', 'b', 'a', 'a', 'b', 'a', 'a', 'b', 'a', 'a', 'b', 'b', 'a',
       'a', 'b', 'a', 'b', 'a', 'a', 'b', 'a', 'a', 'a', 'b', 'a', 'a',
       'b', 'a', 'b', 'a', 'b', 'b', 'b', 'a', 'b', 'b', 'b', 'b', 'b',
       'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'a',
       'b', 'b', 'a', 'a', 'b', 'b', 'a', 'a', 'a', 'b', 'b', 'a

In [48]:
np.unique(y,return_counts=True)

(array(['a', 'b'], dtype='<U1'), array([493, 507], dtype=int64))

by default here both a and b get picked with almost equal probability in the random sample. Although this doesnt mean that individual values are not random , but overall percentage of a and b remains almost same. We can force approx probability structure by using option p

In [49]:
y=np.random.choice(['a','b','c'],100000,p=[0.2,0.4,0.4])

In [50]:
np.unique(y,return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'),
 array([20213, 39969, 39818], dtype=int64))

Another useful function is for sorting 

In [51]:
x=np.random.randint(high=100,low=12,size=(15,))

In [52]:
x.sort()

In [53]:
x

array([19, 30, 34, 35, 35, 35, 39, 58, 59, 61, 61, 67, 80, 97, 99])

Now lets look at sorting 2darrays 

In [54]:
x=np.random.randint(high=100,low=12,size=(4,6))

In [55]:
x

array([[58, 50, 84, 85, 28, 75],
       [28, 27, 38, 19, 86, 98],
       [92, 88, 75, 38, 26, 88],
       [93, 58, 33, 42, 63, 13]])

if we simply sort it sorts each individual array without mainting any order 

In [56]:
x.sort()

In [57]:
x

array([[28, 50, 58, 75, 84, 85],
       [19, 27, 28, 38, 86, 98],
       [26, 38, 75, 88, 88, 92],
       [13, 33, 42, 58, 63, 93]])

In [58]:
x=np.random.randint(high=100,low=12,size=(4,6))
x

array([[66, 87, 13, 37, 82, 97],
       [25, 89, 57, 80, 17, 27],
       [96, 69, 18, 33, 76, 86],
       [29, 84, 84, 94, 31, 55]])

For maintaining order along either of the axis what we can do is that we can extract indices of the sorted values and reorder original array with , here is what i mean

In [59]:
x[:,2]

array([13, 57, 18, 84])

these are the 3rd elements of all arrays , lets i want to sort my 2darray by these and other values should move with them maintaining correspondence

In [60]:

x[:,2].argsort()

array([0, 2, 1, 3], dtype=int64)

what argsort does is that it gives indices of sorted elements , now we can arrange the list along another axes using the result of argsort like this 

In [61]:
x[x[:,2].argsort(),:]

array([[66, 87, 13, 37, 82, 97],
       [96, 69, 18, 33, 76, 86],
       [25, 89, 57, 80, 17, 27],
       [29, 84, 84, 94, 31, 55]])

we can see that correspondence doesnt break here

similar to sort and argsort , another use ful combination at times is max and argmax and its counterparts min and argmin

In [63]:
x=np.random.randint(high=100,low=12,size=(15,))

In [64]:
x

array([38, 95, 40, 92, 69, 17, 86, 40, 29, 62, 68, 55, 16, 18, 87])

In [65]:
x.max()

95

In [66]:
x.argmax()

1